// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCategoryInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewCourseInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	CategoryID  string `json:"categoryId"`
}
